 import pfp1 from "../assets/profile/pfp1.png";
 import bitcoin from "../assets/chains/bitcoin.svg";
 
 const data = [
    {
      name: "mr_froge",
      username: "mr_froge",
      pfp: pfp1,
      bought: true,
      tokenIcon: bitcoin,
      tokenSymbol: "BTC",
      amount: "0.25",
      isMarketUp: true,
      percentage: "1.2",
      copiedTimes: 41,
    },
    {
      name: "mr_froge",
      username: "mr_froge",
      pfp: pfp1,
      bought: true,
      tokenIcon: bitcoin,
      tokenSymbol: "BTC",
      amount: "0.25",
      isMarketUp: true,
      percentage: "1.2",
      copiedTimes: 41,
    },
    {
      name: "mr_froge",
      username: "mr_froge",
      pfp: pfp1,
      bought: true,
      tokenIcon: bitcoin,
      tokenSymbol: "BTC",
      amount: "0.25",
      isMarketUp: true,
      percentage: "1.2",
      copiedTimes: 41,
    },
    {
      name: "mr_froge",
      username: "mr_froge",
      pfp: pfp1,
      bought: true,
      tokenIcon: bitcoin,
      tokenSymbol: "BTC",
      amount: "0.25",
      isMarketUp: true,
      percentage: "1.2",
      copiedTimes: 41,
    },
    {
      name: "mr_froge",
      username: "mr_froge",
      pfp: pfp1,
      bought: true,
      tokenIcon: bitcoin,
      tokenSymbol: "BTC",
      amount: "0.25",
      isMarketUp: true,
      percentage: "1.2",
      copiedTimes: 41,
    },
    {
      name: "mr_froge",
      username: "mr_froge",
      pfp: pfp1,
      bought: true,
      tokenIcon: bitcoin,
      tokenSymbol: "BTC",
      amount: "0.25",
      isMarketUp: true,
      percentage: "1.2",
      copiedTimes: 41,
    },
    {
      name: "mr_froge",
      username: "mr_froge",
      pfp: pfp1,
      bought: true,
      tokenIcon: bitcoin,
      tokenSymbol: "BTC",
      amount: "0.25",
      isMarketUp: true,
      percentage: "1.2",
      copiedTimes: 41,
    },
    {
      name: "mr_froge",
      username: "mr_froge",
      pfp: pfp1,
      bought: true,
      tokenIcon: bitcoin,
      tokenSymbol: "BTC",
      amount: "0.25",
      isMarketUp: true,
      percentage: "1.2",
      copiedTimes: 41,
    },
    {
      name: "mr_froge",
      username: "mr_froge",
      pfp: pfp1,
      bought: true,
      tokenIcon: bitcoin,
      tokenSymbol: "BTC",
      amount: "0.25",
      isMarketUp: true,
      percentage: "1.2",
      copiedTimes: 41,
    },
    {
      name: "mr_froge",
      username: "mr_froge",
      pfp: pfp1,
      bought: true,
      tokenIcon: bitcoin,
      tokenSymbol: "BTC",
      amount: "0.25",
      isMarketUp: true,
      percentage: "1.2",
      copiedTimes: 41,
    },
  ];

  export default data;