import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LeftSidebar from "@/components/LeftSidebar";
import RightSidebar from "@/components/RightSidebar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bloom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-inter  antialiased`}>
        <div className="w-full h-[100dvh] flex bg-white text-black">
          <LeftSidebar />
          <div className="flex-grow h-[100dvh] overflow-y-auto">{children}</div>
          <RightSidebar />
        </div>
      </body>
    </html>
  );
}
